
import { Medicine, MedicineCategory } from './types';

// Helper to generate dynamic dates for demo purposes
// This ensures "Expiring Soon" logic works regardless of when the app is run
const getFutureDate = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const MEDICINES: Medicine[] = [
  {
    id: 'med_1',
    name: 'Paracetamol 650mg',
    brandExample: 'Dolo 650 / Crocin',
    saltComposition: 'Paracetamol (Acetaminophen) IP 650mg',
    batchNumber: 'PCM-2023-001',
    category: MedicineCategory.FEVER,
    commonUse: ['Fever', 'Mild Pain', 'Headache'],
    description: 'The most common medicine in India for fever and body ache. Safe for most adults when taken correctly.',
    genericPrice: 10.50,
    brandedPrice: 30.00,
    stock: 150,
    expiryDate: getFutureDate(365), // 1 Year valid
    marketRates: [
      { shopName: 'Jan Aushadhi (Govt)', price: 10.50, type: 'Generic' },
      { shopName: 'Local Chemist', price: 30.00, type: 'Branded' },
      { shopName: 'Apollo Pharmacy', price: 28.50, type: 'Branded' },
      { shopName: 'Tata 1mg', price: 25.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: {
      normal: '1 tablet every 6-8 hours as needed.',
      maxSafe: 'Do not exceed 3-4g (approx 4-6 tablets) in 24 hours.',
      overdoseWarning: 'Liver damage (Hepatotoxicity) can occur with overdose.',
    },
    details: {
      mechanism: 'Blocks chemical messengers in the brain that tell us we have pain and regulates body temperature.',
      sideEffects: ['Nausea', 'Vomiting', 'Allergic skin reaction (rare)'],
      contraindications: ['Severe liver disease', 'Alcoholism'],
      storage: 'Store in a cool, dry place away from sunlight.',
    },
  },
  {
    id: 'med_2',
    name: 'Pantoprazole 40mg',
    brandExample: 'Pan 40 / Pantocid',
    saltComposition: 'Pantoprazole Sodium IP 40mg (Enteric Coated)',
    batchNumber: 'PAN-23-X89',
    category: MedicineCategory.ACIDITY,
    commonUse: ['Acidity', 'Heartburn', 'GERD', 'Gastritis'],
    description: 'Effective for acidity and gas issues, often prescribed for acid reflux and stomach ulcers.',
    genericPrice: 42.00,
    brandedPrice: 155.00,
    stock: 120,
    expiryDate: getFutureDate(400),
    marketRates: [
      { shopName: 'Jan Aushadhi (Govt)', price: 42.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 155.00, type: 'Branded' },
      { shopName: 'Netmeds', price: 130.00, type: 'Branded' },
      { shopName: 'PharmEasy', price: 125.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2d5f926?auto=format&fit=crop&q=80&w=800',
    dosage: {
      normal: '1 tablet daily, 1 hour before breakfast.',
      maxSafe: 'Consult doctor for long term use.',
      overdoseWarning: 'Generally safe, but long term misuse can affect bone density.',
    },
    details: {
      mechanism: 'A Proton Pump Inhibitor (PPI) that reduces the amount of acid produced in the stomach.',
      sideEffects: ['Headache', 'Diarrhea', 'Stomach pain', 'Flatulence'],
      contraindications: ['Hypersensitivity to PPIs', 'Low magnesium levels'],
      storage: 'Keep at room temperature.',
    },
  },
  {
    id: 'med_exp_1',
    name: 'Cetirizine 10mg (Expiring)',
    brandExample: 'Cetzine / Okacet',
    saltComposition: 'Cetirizine Hydrochloride IP 10mg',
    batchNumber: 'CET-OLD-01',
    category: MedicineCategory.ALLERGY,
    commonUse: ['Allergy', 'Running Nose', 'Sneezing', 'Itching'],
    description: 'Non-drowsy anti-allergic for seasonal allergies, hives, and skin rashes.',
    genericPrice: 12.00, // Discounted
    brandedPrice: 45.00,
    stock: 20,
    expiryDate: getFutureDate(15), // Expiring in 15 days
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 12.00, type: 'Generic' },
      { shopName: 'Local Pharmacy', price: 45.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: {
      normal: '1 tablet once daily.',
      maxSafe: '10mg per day.',
      overdoseWarning: 'Excessive drowsiness.',
    },
    details: {
      mechanism: 'Blocks histamine.',
      sideEffects: ['Sleepiness', 'Dry mouth'],
      contraindications: ['Severe kidney failure'],
      storage: 'Store below 30°C.',
    },
  },
  // ... Adding new valid medicines
  {
    id: 'med_new_1',
    name: 'Ondansetron 4mg',
    brandExample: 'Emeset 4 / Vomikind',
    saltComposition: 'Ondansetron IP 4mg',
    batchNumber: 'OND-25-A01',
    category: MedicineCategory.ACIDITY,
    commonUse: ['Nausea', 'Vomiting', 'Motion Sickness'],
    description: 'Effective anti-emetic medicine used to prevent nausea and vomiting caused by chemotherapy or surgery.',
    genericPrice: 12.00,
    brandedPrice: 55.00,
    stock: 200,
    expiryDate: getFutureDate(730),
    marketRates: [
        { shopName: 'Jan Aushadhi', price: 12.00, type: 'Generic' },
        { shopName: 'Local Chemist', price: 55.00, type: 'Branded' }
    ],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: {
        normal: '1 tablet as needed, usually 30 mins before meal.',
        maxSafe: '8mg per dose.',
        overdoseWarning: 'Vision problems, severe constipation.',
    },
    details: {
        mechanism: 'Blocks the action of serotonin that triggers nausea.',
        sideEffects: ['Constipation', 'Headache', 'Flushing'],
        contraindications: ['Apomorphine usage'],
        storage: 'Store in a cool dry place.',
    },
  },
  {
    id: 'med_new_2',
    name: 'Thyroxine 50mcg',
    brandExample: 'Thyronorm 50',
    saltComposition: 'Thyroxine Sodium IP 50mcg',
    batchNumber: 'THY-25-B99',
    category: MedicineCategory.SUPPLEMENTS, // Broadly fits here or a new category
    commonUse: ['Hypothyroidism', 'Thyroid deficiency'],
    description: 'Synthetic thyroid hormone to replace what the body is not producing.',
    genericPrice: 45.00,
    brandedPrice: 130.00,
    stock: 150,
    expiryDate: getFutureDate(500),
    marketRates: [
        { shopName: 'Jan Aushadhi', price: 45.00, type: 'Generic' },
        { shopName: 'Local Chemist', price: 130.00, type: 'Branded' }
    ],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: {
        normal: '1 tablet empty stomach early morning.',
        maxSafe: 'As prescribed.',
        overdoseWarning: 'Palpitations, weight loss, tremors.',
    },
    details: {
        mechanism: 'Replenishes thyroid hormone levels.',
        sideEffects: ['Anxiety', 'Diarrhea'],
        contraindications: ['Thyrotoxicosis'],
        storage: 'Protect from light.',
    },
  },
  {
    id: 'med_new_3',
    name: 'Ursodeoxycholic Acid 300mg',
    brandExample: 'Udiliv 300',
    saltComposition: 'Ursodeoxycholic Acid IP 300mg',
    batchNumber: 'UDC-25-L88',
    category: MedicineCategory.ACIDITY, // Digestive health
    commonUse: ['Liver Health', 'Gallstones'],
    description: 'Hepatoprotective medicine used to dissolve gallstones and improve liver function.',
    genericPrice: 150.00,
    brandedPrice: 450.00,
    stock: 80,
    expiryDate: getFutureDate(300),
    marketRates: [
        { shopName: 'Jan Aushadhi', price: 150.00, type: 'Generic' },
        { shopName: 'Local Chemist', price: 450.00, type: 'Branded' }
    ],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: {
        normal: '1 tablet twice daily after meals.',
        maxSafe: 'As prescribed.',
        overdoseWarning: 'Diarrhea.',
    },
    details: {
        mechanism: 'Decreases cholesterol production in bile.',
        sideEffects: ['Diarrhea', 'Nausea', 'Back pain'],
        contraindications: ['Acute inflammation of gallbladder'],
        storage: 'Store at room temperature.',
    },
  },
  {
    id: 'med_new_4',
    name: 'Itraconazole 100mg',
    brandExample: 'Candiforce 100',
    saltComposition: 'Itraconazole IP 100mg',
    batchNumber: 'ITR-25-F77',
    category: MedicineCategory.ANTIBIOTIC, // Antifungal
    commonUse: ['Fungal Infection', 'Ringworm', 'Nail Infection'],
    description: 'Potent antifungal medication used for treating various fungal infections.',
    genericPrice: 80.00,
    brandedPrice: 220.00,
    stock: 100,
    expiryDate: getFutureDate(600),
    marketRates: [
        { shopName: 'Jan Aushadhi', price: 80.00, type: 'Generic' },
        { shopName: 'Local Chemist', price: 220.00, type: 'Branded' }
    ],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: {
        normal: '1 capsule twice daily after meals.',
        maxSafe: 'As prescribed.',
        overdoseWarning: 'Liver toxicity.',
    },
    details: {
        mechanism: 'Inhibits synthesis of ergosterol in fungal cell membrane.',
        sideEffects: ['Nausea', 'Common cold', 'Cough'],
        contraindications: ['Heart failure'],
        storage: 'Store below 25°C.',
    },
  },
  {
    id: 'med_exp_2',
    name: 'Calcium + Vit D3 (Short Expiry)',
    brandExample: 'Shelcal 500',
    saltComposition: 'Calcium Carbonate 500mg + Vitamin D3 250 IU',
    batchNumber: 'CAL-OLD-88',
    category: MedicineCategory.SUPPLEMENTS,
    commonUse: ['Bone Health', 'Calcium Deficiency'],
    description: 'Clearance stock: Essential supplement for strong bones.',
    genericPrice: 30.00, // Clearance price
    brandedPrice: 125.00,
    stock: 40,
    expiryDate: getFutureDate(10), // 10 days left
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1551241855-44243a0e6981?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 tablet daily.', maxSafe: 'Consult doctor.', overdoseWarning: 'Kidney stones.' },
    details: { mechanism: 'Calcium supplement.', sideEffects: ['Gas'], contraindications: ['Hypercalcemia'], storage: 'Keep dry.' },
  },
  {
    id: 'med_new_5',
    name: 'Mefenamic Acid 500mg',
    brandExample: 'Meftal 500',
    saltComposition: 'Mefenamic Acid IP 500mg',
    batchNumber: 'MEF-25-P22',
    category: MedicineCategory.PAIN,
    commonUse: ['Period Pain', 'Dental Pain', 'Muscle Pain'],
    description: 'NSAID used for short-term relief of mild to moderate pain.',
    genericPrice: 15.00,
    brandedPrice: 40.00,
    stock: 120,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 tablet thrice daily after food.', maxSafe: 'Short term use.', overdoseWarning: 'Seizures.' },
    details: { mechanism: 'Inhibits prostaglandin synthesis.', sideEffects: ['Diarrhea', 'Nausea'], contraindications: ['Ulcers'], storage: 'Cool dry place.' },
  },
  {
    id: 'med_new_6',
    name: 'Vildagliptin 50mg',
    brandExample: 'Galvus 50',
    saltComposition: 'Vildagliptin IP 50mg',
    batchNumber: 'VIL-25-D11',
    category: MedicineCategory.DIABETES,
    commonUse: ['Type 2 Diabetes'],
    description: 'DPP-4 inhibitor used to improve blood sugar control.',
    genericPrice: 45.00,
    brandedPrice: 180.00,
    stock: 90,
    expiryDate: getFutureDate(450),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 tablet twice daily.', maxSafe: '100mg daily.', overdoseWarning: 'Hypoglycemia.' },
    details: { mechanism: 'Increases insulin release.', sideEffects: ['Dizziness', 'Headache'], contraindications: ['Liver disease'], storage: 'Room temp.' },
  },
  {
    id: 'med_new_7',
    name: 'Clopidogrel 75mg',
    brandExample: 'Plavix / Clavix',
    saltComposition: 'Clopidogrel Bisulfate IP 75mg',
    batchNumber: 'CLO-25-H33',
    category: MedicineCategory.HEART,
    commonUse: ['Heart Attack Prevention', 'Stroke Prevention'],
    description: 'Antiplatelet medicine to prevent blood clots.',
    genericPrice: 35.00,
    brandedPrice: 110.00,
    stock: 140,
    expiryDate: getFutureDate(600),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 tablet daily.', maxSafe: '75mg daily.', overdoseWarning: 'Bleeding.' },
    details: { mechanism: 'Prevents platelets from sticking together.', sideEffects: ['Bleeding', 'Bruising'], contraindications: ['Active bleeding'], storage: 'Dry place.' },
  },
  {
    id: 'med_exp_3',
    name: 'Azithromycin 500mg (Expiring)',
    brandExample: 'Azithral 500',
    saltComposition: 'Azithromycin IP 500mg',
    batchNumber: 'AZI-OLD-99',
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['Throat Infection'],
    description: 'Antibiotic stock clearing out.',
    genericPrice: 40.00,
    brandedPrice: 120.00,
    stock: 15,
    expiryDate: getFutureDate(25), // 25 days left
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 daily.', maxSafe: 'As prescribed.', overdoseWarning: 'Liver toxicity.' },
    details: { mechanism: 'Antibiotic.', sideEffects: ['Diarrhea'], contraindications: ['Liver issues'], storage: 'Cool dry place.' },
  },
  {
    id: 'med_new_8',
    name: 'Levosalbutamol Syrup',
    brandExample: 'Asthalin LS',
    saltComposition: 'Levosalbutamol 1mg/5ml',
    batchNumber: 'LEV-25-R44',
    category: MedicineCategory.COLD_FLU, // Respiratory
    commonUse: ['Asthma', 'Bronchitis', 'Cough'],
    description: 'Bronchodilator used to relieve coughing and shortness of breath.',
    genericPrice: 25.00,
    brandedPrice: 85.00,
    stock: 100,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2d5f926?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '5-10ml thrice daily.', maxSafe: 'As prescribed.', overdoseWarning: 'Palpitations.' },
    details: { mechanism: 'Relaxes muscles in airways.', sideEffects: ['Tremors', 'Heart rate increase'], contraindications: ['Heart disease'], storage: 'Dark place.' },
  },
  // Keep some original valid ones
  {
    id: 'med_4',
    name: 'Azithromycin 500mg',
    brandExample: 'Azithral 500',
    saltComposition: 'Azithromycin IP 500mg',
    batchNumber: 'AZI-23-M55',
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['Throat Infection', 'Bacterial Infection', 'Typhoid'],
    description: 'A macrolide antibiotic used for respiratory, throat, and skin infections.',
    genericPrice: 60.00,
    brandedPrice: 120.00,
    stock: 50,
    expiryDate: getFutureDate(180), // 6 months
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 60.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 120.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    dosage: {
      normal: '1 tablet daily for 3 to 5 days.',
      maxSafe: 'Strictly follow doctor prescription.',
      overdoseWarning: 'Liver toxicity and irregular heart rhythm.',
    },
    details: {
      mechanism: 'Stops bacterial growth by inhibiting synthesis of essential proteins.',
      sideEffects: ['Diarrhea', 'Abdominal pain', 'Nausea'],
      contraindications: ['Liver problems', 'History of jaundice with this med'],
      storage: 'Store in a cool dry place.',
    },
  },
  {
    id: 'med_5',
    name: 'Metformin 500mg',
    brandExample: 'Glycomet 500',
    saltComposition: 'Metformin Hydrochloride IP 500mg',
    batchNumber: 'MET-24-D99',
    category: MedicineCategory.DIABETES,
    commonUse: ['Type 2 Diabetes', 'Blood Sugar Control'],
    description: 'Standard first-line medication for the treatment of type 2 diabetes mellitus.',
    genericPrice: 18.00,
    brandedPrice: 45.00,
    stock: 180,
    expiryDate: getFutureDate(400),
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 18.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 45.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=800',
    dosage: {
      normal: 'As prescribed (usually with meals).',
      maxSafe: 'Max 2000-2500mg daily in divided doses.',
      overdoseWarning: 'Lactic acidosis (rare but serious metabolic complication).',
    },
    details: {
      mechanism: 'Decreases glucose production by the liver and improves insulin sensitivity.',
      sideEffects: ['Nausea', 'Stomach upset', 'Metallic taste'],
      contraindications: ['Severe kidney disease', 'Metabolic acidosis'],
      storage: 'Store at room temperature.',
    },
  }
];

export const ANIMATIONS = {
    fadeIn: "animate-fade-in",
    slideUp: "animate-slide-up"
};
