import { Medicine, MedicineCategory } from './types';

export const MEDICINES: Medicine[] = [
  {
    id: 'med_1',
    name: 'Paracetamol 650mg',
    brandExample: 'Dolo 650 / Crocin',
    saltComposition: 'Paracetamol (Acetaminophen) IP 650mg',
    category: MedicineCategory.FEVER,
    commonUse: ['Fever', 'Mild Pain', 'Headache'],
    description: 'The most common medicine in India for fever and body ache. Safe for most adults when taken correctly.',
    genericPrice: 10.50,
    brandedPrice: 30.00,
    marketRates: [
      { shopName: 'Jan Aushadhi (Govt)', price: 10.50, type: 'Generic' },
      { shopName: 'Local Chemist', price: 30.00, type: 'Branded' },
      { shopName: 'Apollo Pharmacy', price: 28.50, type: 'Branded' },
      { shopName: 'Tata 1mg', price: 25.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet every 6-8 hours as needed.',
      maxSafe: 'Do not exceed 3-4g (approx 4-6 tablets) in 24 hours.',
      overdoseWarning: 'Liver damage (Hepatotoxicity) can occur with overdose.',
    },
    details: {
      mechanism: 'Blocks chemical messengers in the brain that tell us we have pain and regulates body temperature.',
      sideEffects: ['Nausea', 'Vomiting', 'Allergic skin reaction (rare)'],
      contraindications: ['Severe liver disease', 'Alcoholism'],
      storage: 'Store in a cool, dry place away from sunlight.',
    },
  },
  {
    id: 'med_2',
    name: 'Pantoprazole 40mg',
    brandExample: 'Pan 40 / Pantocid',
    saltComposition: 'Pantoprazole Sodium IP 40mg (Enteric Coated)',
    category: MedicineCategory.ACIDITY,
    commonUse: ['Acidity', 'Heartburn', 'GERD', 'Gastritis'],
    description: 'Effective for acidity and gas issues, often prescribed for acid reflux and stomach ulcers.',
    genericPrice: 42.00,
    brandedPrice: 155.00,
    marketRates: [
      { shopName: 'Jan Aushadhi (Govt)', price: 42.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 155.00, type: 'Branded' },
      { shopName: 'Netmeds', price: 130.00, type: 'Branded' },
      { shopName: 'PharmEasy', price: 125.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet daily, 1 hour before breakfast.',
      maxSafe: 'Consult doctor for long term use.',
      overdoseWarning: 'Generally safe, but long term misuse can affect bone density.',
    },
    details: {
      mechanism: 'A Proton Pump Inhibitor (PPI) that reduces the amount of acid produced in the stomach.',
      sideEffects: ['Headache', 'Diarrhea', 'Stomach pain', 'Flatulence'],
      contraindications: ['Hypersensitivity to PPIs', 'Low magnesium levels'],
      storage: 'Keep at room temperature.',
    },
  },
  {
    id: 'med_3',
    name: 'Cetirizine 10mg',
    brandExample: 'Cetzine / Okacet',
    saltComposition: 'Cetirizine Hydrochloride IP 10mg',
    category: MedicineCategory.ALLERGY,
    commonUse: ['Allergy', 'Running Nose', 'Sneezing', 'Itching'],
    description: 'Non-drowsy anti-allergic for seasonal allergies, hives, and skin rashes.',
    genericPrice: 15.00,
    brandedPrice: 45.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 15.00, type: 'Generic' },
      { shopName: 'Local Pharmacy', price: 45.00, type: 'Branded' },
      { shopName: 'Apollo', price: 42.00, type: 'Branded' },
      { shopName: 'Generickart', price: 18.00, type: 'Generic' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet once daily, preferably at night.',
      maxSafe: '10mg per day for adults.',
      overdoseWarning: 'Excessive drowsiness, sedation, and dry mouth.',
    },
    details: {
      mechanism: 'Blocks histamine, a chemical messenger involved in allergic reactions.',
      sideEffects: ['Sleepiness', 'Dry mouth', 'Fatigue'],
      contraindications: ['Severe kidney failure', 'Breastfeeding mothers (consult doctor)'],
      storage: 'Store below 30°C.',
    },
  },
  {
    id: 'med_4',
    name: 'Azithromycin 500mg',
    brandExample: 'Azithral 500',
    saltComposition: 'Azithromycin IP 500mg',
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['Throat Infection', 'Bacterial Infection', 'Typhoid'],
    description: 'A macrolide antibiotic used for respiratory, throat, and skin infections.',
    genericPrice: 60.00,
    brandedPrice: 120.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 60.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 120.00, type: 'Branded' },
      { shopName: 'Netmeds', price: 105.00, type: 'Branded' },
      { shopName: '1mg', price: 100.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet daily for 3 to 5 days.',
      maxSafe: 'Strictly follow doctor prescription.',
      overdoseWarning: 'Liver toxicity and irregular heart rhythm.',
    },
    details: {
      mechanism: 'Stops bacterial growth by inhibiting synthesis of essential proteins.',
      sideEffects: ['Diarrhea', 'Abdominal pain', 'Nausea'],
      contraindications: ['Liver problems', 'History of jaundice with this med'],
      storage: 'Store in a cool dry place.',
    },
  },
  {
    id: 'med_5',
    name: 'Metformin 500mg',
    brandExample: 'Glycomet 500',
    saltComposition: 'Metformin Hydrochloride IP 500mg',
    category: MedicineCategory.DIABETES,
    commonUse: ['Type 2 Diabetes', 'Blood Sugar Control'],
    description: 'Standard first-line medication for the treatment of type 2 diabetes mellitus.',
    genericPrice: 18.00,
    brandedPrice: 45.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 18.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 45.00, type: 'Branded' },
      { shopName: 'Apollo', price: 40.00, type: 'Branded' },
      { shopName: 'Truemeds', price: 25.00, type: 'Generic' },
    ],
    imageUrl: 'https://plus.unsplash.com/premium_photo-1668487826871-2f2cac436ec1?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: 'As prescribed (usually with meals).',
      maxSafe: 'Max 2000-2500mg daily in divided doses.',
      overdoseWarning: 'Lactic acidosis (rare but serious metabolic complication).',
    },
    details: {
      mechanism: 'Decreases glucose production by the liver and improves insulin sensitivity.',
      sideEffects: ['Nausea', 'Stomach upset', 'Metallic taste'],
      contraindications: ['Severe kidney disease', 'Metabolic acidosis'],
      storage: 'Store at room temperature.',
    },
  },
  {
    id: 'med_6',
    name: 'Ibuprofen 400mg',
    brandExample: 'Brufen 400',
    saltComposition: 'Ibuprofen IP 400mg',
    category: MedicineCategory.PAIN,
    commonUse: ['Pain Relief', 'Inflammation', 'Joint Pain'],
    description: 'A powerful painkiller and anti-inflammatory drug for muscles and joints.',
    genericPrice: 8.00,
    brandedPrice: 20.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 8.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 20.00, type: 'Branded' },
      { shopName: 'PharmEasy', price: 18.00, type: 'Branded' },
      { shopName: 'Generic Store', price: 10.00, type: 'Generic' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet every 8 hours after food.',
      maxSafe: '1200mg-2400mg depending on severity (consult doctor).',
      overdoseWarning: 'Stomach bleeding, kidney damage.',
    },
    details: {
      mechanism: 'Non-steroidal anti-inflammatory drug (NSAID) that reduces hormones causing pain and inflammation.',
      sideEffects: ['Heartburn', 'Stomach pain', 'Nausea'],
      contraindications: ['Stomach ulcers', 'Asthma', 'Heart disease'],
      storage: 'Store away from moisture.',
    },
  },
  {
    id: 'med_7',
    name: 'Amoxicillin 500mg',
    brandExample: 'Mox 500 / Novamox',
    saltComposition: 'Amoxicillin Trihydrate IP 500mg',
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['Ear Infection', 'Pneumonia', 'Skin Infection'],
    description: 'A widely used penicillin-type antibiotic for various bacterial infections.',
    genericPrice: 45.00,
    brandedPrice: 110.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 45.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 110.00, type: 'Branded' },
      { shopName: 'Apollo', price: 105.00, type: 'Branded' },
      { shopName: '1mg', price: 100.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 capsule every 8 hours.',
      maxSafe: 'As prescribed by physician.',
      overdoseWarning: 'Kidney failure, crystalluria.',
    },
    details: {
      mechanism: 'Kills bacteria by preventing them from building a protective cell wall.',
      sideEffects: ['Rash', 'Diarrhea', 'Yeast infection'],
      contraindications: ['Penicillin allergy', 'Mononucleosis'],
      storage: 'Keep dry and cool.',
    },
  },
  {
    id: 'med_8',
    name: 'Atorvastatin 10mg',
    brandExample: 'Atorva 10 / Lipitor',
    saltComposition: 'Atorvastatin Calcium IP 10mg',
    category: MedicineCategory.HEART,
    commonUse: ['High Cholesterol', 'Heart Attack Prevention'],
    description: 'Statin medication used to lower bad cholesterol (LDL) and triglycerides.',
    genericPrice: 35.00,
    brandedPrice: 85.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 35.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 85.00, type: 'Branded' },
      { shopName: 'Netmeds', price: 75.00, type: 'Branded' },
      { shopName: 'Truemeds', price: 45.00, type: 'Generic' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1471864190276-a9468523011e?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: 'Once daily at any time (usually night).',
      maxSafe: '80mg per day.',
      overdoseWarning: 'Muscle damage (Rhabdomyolysis), liver toxicity.',
    },
    details: {
      mechanism: 'Blocks an enzyme needed by the body to make cholesterol.',
      sideEffects: ['Muscle pain', 'Weakness', 'Digestive issues'],
      contraindications: ['Active liver disease', 'Pregnancy'],
      storage: 'Store below 25°C.',
    },
  },
  {
    id: 'med_9',
    name: 'Calcium + Vit D3',
    brandExample: 'Shelcal 500',
    saltComposition: 'Calcium Carbonate 500mg + Vitamin D3 250 IU',
    category: MedicineCategory.SUPPLEMENTS,
    commonUse: ['Bone Health', 'Calcium Deficiency', 'Osteoporosis'],
    description: 'Essential supplement for strong bones, teeth and joints.',
    genericPrice: 55.00,
    brandedPrice: 125.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 55.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 125.00, type: 'Branded' },
      { shopName: 'Apollo', price: 120.00, type: 'Branded' },
      { shopName: 'PharmEasy', price: 110.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1551241855-44243a0e6981?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet daily after food.',
      maxSafe: 'Consult doctor for high doses.',
      overdoseWarning: 'Kidney stones, hypercalcemia.',
    },
    details: {
      mechanism: 'Calcium builds bone; Vitamin D3 helps the body absorb Calcium.',
      sideEffects: ['Constipation', 'Gas', 'Bloating'],
      contraindications: ['Hypercalcemia', 'Severe kidney failure'],
      storage: 'Keep container tightly closed.',
    },
  },
  {
    id: 'med_10',
    name: 'B-Complex + Vit C',
    brandExample: 'Becosules Z',
    saltComposition: 'Vitamin B-Complex (B1, B2, B6, B12) + Vitamin C + Zinc',
    category: MedicineCategory.SUPPLEMENTS,
    commonUse: ['Mouth Ulcers', 'Immunity', 'Weakness'],
    description: 'Multivitamin supplement for overall health, immunity and recovery.',
    genericPrice: 25.00,
    brandedPrice: 50.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 25.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 50.00, type: 'Branded' },
      { shopName: 'Apollo', price: 48.00, type: 'Branded' },
      { shopName: 'Generickart', price: 28.00, type: 'Generic' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1574567675988-1f6f890693a9?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 capsule daily after a meal.',
      maxSafe: '1 capsule daily.',
      overdoseWarning: 'Nerve damage (rare, from excess B6).',
    },
    details: {
      mechanism: 'Replenishes essential water-soluble vitamins needed for metabolism.',
      sideEffects: ['Bright yellow urine (harmless)', 'Nausea'],
      contraindications: ['Known allergy to components'],
      storage: 'Store in a cool dry place.',
    },
  },
  {
    id: 'med_11',
    name: 'Telmisartan 40mg',
    brandExample: 'Telma 40',
    saltComposition: 'Telmisartan IP 40mg',
    category: MedicineCategory.HEART,
    commonUse: ['High Blood Pressure', 'Heart Failure', 'Stroke Prevention'],
    description: 'Used to treat high blood pressure (hypertension) and reduce cardiovascular risk.',
    genericPrice: 25.00,
    brandedPrice: 120.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 25.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 120.00, type: 'Branded' },
      { shopName: 'Apollo', price: 110.00, type: 'Branded' },
      { shopName: '1mg', price: 100.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2d5f926?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet daily, usually in the morning.',
      maxSafe: '80mg per day as prescribed.',
      overdoseWarning: 'Low blood pressure, dizziness, kidney impact.',
    },
    details: {
      mechanism: 'Relaxes blood vessels so blood can flow more easily (Angiotensin Receptor Blocker).',
      sideEffects: ['Sinus pain', 'Back pain', 'Diarrhea'],
      contraindications: ['Pregnancy', 'Severe liver impairment'],
      storage: 'Store away from moisture.',
    },
  },
  {
    id: 'med_12',
    name: 'Montelukast + Levocetirizine',
    brandExample: 'Montair LC',
    saltComposition: 'Montelukast 10mg + Levocetirizine 5mg',
    category: MedicineCategory.ALLERGY,
    commonUse: ['Allergic Rhinitis', 'Asthma', 'Dust Allergy'],
    description: 'Combination medicine for treating symptoms of allergic rhinitis and asthma.',
    genericPrice: 40.00,
    brandedPrice: 180.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 40.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 180.00, type: 'Branded' },
      { shopName: 'Netmeds', price: 160.00, type: 'Branded' },
      { shopName: 'PharmEasy', price: 150.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet daily at bedtime.',
      maxSafe: '1 tablet daily.',
      overdoseWarning: 'Drowsiness, restlessness, thirst.',
    },
    details: {
      mechanism: 'Levocetirizine blocks histamine (allergy); Montelukast blocks leukotrienes (inflammation).',
      sideEffects: ['Dry mouth', 'Headache', 'Sleepiness'],
      contraindications: ['Kidney disease', 'Severe liver disease'],
      storage: 'Store protected from light.',
    },
  },
  {
    id: 'med_13',
    name: 'Omeprazole 20mg',
    brandExample: 'Omez 20',
    saltComposition: 'Omeprazole IP 20mg',
    category: MedicineCategory.ACIDITY,
    commonUse: ['Acidity', 'Stomach Ulcers', 'Acid Reflux'],
    description: 'Reduces the amount of acid your stomach makes. Treats heartburn and indigestion.',
    genericPrice: 15.00,
    brandedPrice: 55.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 15.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 55.00, type: 'Branded' },
      { shopName: 'Apollo', price: 50.00, type: 'Branded' },
      { shopName: '1mg', price: 45.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 capsule in the morning before food.',
      maxSafe: 'As prescribed (short term).',
      overdoseWarning: 'Confusion, drowsiness, blurred vision.',
    },
    details: {
      mechanism: 'Proton pump inhibitor (PPI) that blocks acid production.',
      sideEffects: ['Headache', 'Stomach pain', 'Gas'],
      contraindications: ['Allergy to PPIs', 'Osteoporosis (long term use)'],
      storage: 'Store below 25°C.',
    },
  },
  {
    id: 'med_14',
    name: 'Diclofenac 50mg',
    brandExample: 'Voveran 50',
    saltComposition: 'Diclofenac Sodium IP 50mg',
    category: MedicineCategory.PAIN,
    commonUse: ['Muscle Pain', 'Arthritis', 'Back Pain', 'Sprains'],
    description: 'Potent non-steroidal anti-inflammatory drug (NSAID) for pain relief.',
    genericPrice: 10.00,
    brandedPrice: 45.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 10.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 45.00, type: 'Branded' },
      { shopName: 'PharmEasy', price: 40.00, type: 'Branded' },
      { shopName: 'Netmeds', price: 38.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet 2-3 times a day after food.',
      maxSafe: '150mg per day.',
      overdoseWarning: 'Kidney failure, stomach bleeding.',
    },
    details: {
      mechanism: 'Reduces substances in the body that cause pain and inflammation.',
      sideEffects: ['Indigestion', 'Gas', 'Nausea'],
      contraindications: ['Heart surgery recovery', 'Stomach ulcers'],
      storage: 'Keep dry.',
    },
  },
  {
    id: 'med_15',
    name: 'Amlodipine 5mg',
    brandExample: 'Amlong 5',
    saltComposition: 'Amlodipine Besylate IP 5mg',
    category: MedicineCategory.HEART,
    commonUse: ['High Blood Pressure', 'Angina (Chest Pain)'],
    description: 'Calcium channel blocker used to control high blood pressure.',
    genericPrice: 8.00,
    brandedPrice: 35.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 8.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 35.00, type: 'Branded' },
      { shopName: 'Apollo', price: 30.00, type: 'Branded' },
      { shopName: 'Truemeds', price: 12.00, type: 'Generic' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1471864190276-a9468523011e?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet daily.',
      maxSafe: '10mg daily.',
      overdoseWarning: 'Severe hypotension, fast heartbeat.',
    },
    details: {
      mechanism: 'Relaxes blood vessels allowing blood to pass more easily.',
      sideEffects: ['Swelling of ankles (Edema)', 'Tiredness', 'Flushing'],
      contraindications: ['Low blood pressure', 'Liver failure'],
      storage: 'Store protected from light.',
    },
  },
  {
    id: 'med_16',
    name: 'Metronidazole 400mg',
    brandExample: 'Flagyl 400',
    saltComposition: 'Metronidazole IP 400mg',
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['Stomach Infection', 'Dental Infection', 'Loose Motion'],
    description: 'Antibiotic effective against anaerobic bacteria and certain parasites.',
    genericPrice: 12.00,
    brandedPrice: 25.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 12.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 25.00, type: 'Branded' },
      { shopName: 'Apollo', price: 22.00, type: 'Branded' },
      { shopName: '1mg', price: 20.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet every 8 hours after food.',
      maxSafe: 'As prescribed (short course).',
      overdoseWarning: 'Nausea, vomiting, nerve damage (neuropathy).',
    },
    details: {
      mechanism: 'Damages the DNA of the bacteria or parasite causing it to die.',
      sideEffects: ['Metallic taste', 'Nausea', 'Dark urine'],
      contraindications: ['Alcohol consumption (strict no)', 'First trimester pregnancy'],
      storage: 'Store below 30°C.',
    },
  },
  {
    id: 'med_17',
    name: 'Domperidone 10mg',
    brandExample: 'Domstal 10',
    saltComposition: 'Domperidone IP 10mg',
    category: MedicineCategory.ACIDITY,
    commonUse: ['Nausea', 'Vomiting', 'Indigestion'],
    description: 'Prokinetic medicine used to treat nausea and vomiting.',
    genericPrice: 10.00,
    brandedPrice: 30.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 10.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 30.00, type: 'Branded' },
      { shopName: 'Netmeds', price: 25.00, type: 'Branded' },
      { shopName: 'PharmEasy', price: 24.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet before meals (15-30 mins).',
      maxSafe: '30mg per day (usually).',
      overdoseWarning: 'Irregular heartbeat, drowsiness.',
    },
    details: {
      mechanism: 'Increases the movement of food through the stomach and digestive tract.',
      sideEffects: ['Dry mouth', 'Headache'],
      contraindications: ['Heart problems', 'Bleeding in stomach'],
      storage: 'Store in a dry place.',
    },
  },
  {
    id: 'med_18',
    name: 'Aceclofenac + Paracetamol',
    brandExample: 'Zerodol P',
    saltComposition: 'Aceclofenac 100mg + Paracetamol 325mg',
    category: MedicineCategory.PAIN,
    commonUse: ['Joint Pain', 'Fever', 'Body Ache'],
    description: 'Combination medicine used for pain relief and fever reduction.',
    genericPrice: 25.00,
    brandedPrice: 65.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 25.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 65.00, type: 'Branded' },
      { shopName: 'Apollo', price: 60.00, type: 'Branded' },
      { shopName: '1mg', price: 55.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet twice daily after food.',
      maxSafe: '2 tablets daily.',
      overdoseWarning: 'Liver damage, stomach ulcers.',
    },
    details: {
      mechanism: 'Blocks the release of chemical messengers that cause pain and fever.',
      sideEffects: ['Nausea', 'Vomiting', 'Stomach pain'],
      contraindications: ['Liver disease', 'Kidney disease'],
      storage: 'Store in a cool dry place.',
    },
  },
  {
    id: 'med_19',
    name: 'Vitamin E 400mg',
    brandExample: 'Evion 400',
    saltComposition: 'Tocopheryl Acetate (Vitamin E) 400mg',
    category: MedicineCategory.SUPPLEMENTS,
    commonUse: ['Skin Health', 'Hair Health', 'Muscle Cramps'],
    description: 'Fat-soluble antioxidant vitamin supplement.',
    genericPrice: 18.00,
    brandedPrice: 38.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 18.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 38.00, type: 'Branded' },
      { shopName: 'Netmeds', price: 35.00, type: 'Branded' },
      { shopName: 'PharmEasy', price: 32.00, type: 'Branded' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1551241855-44243a0e6981?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 capsule daily.',
      maxSafe: 'Consult doctor for high dosage.',
      overdoseWarning: 'Bleeding risk, fatigue.',
    },
    details: {
      mechanism: 'Protects cells from damage caused by free radicals (antioxidant).',
      sideEffects: ['Nausea', 'Tiredness', 'Headache'],
      contraindications: ['Vitamin K deficiency', 'Bleeding disorders'],
      storage: 'Store below 25°C.',
    },
  },
  {
    id: 'med_20',
    name: 'Methylcobalamin 1500mcg',
    brandExample: 'Nurokind OD',
    saltComposition: 'Methylcobalamin (Vitamin B12) 1500mcg',
    category: MedicineCategory.SUPPLEMENTS,
    commonUse: ['Nerve Health', 'B12 Deficiency', 'Anemia'],
    description: 'Active form of Vitamin B12 essential for nerve function and red blood cell formation.',
    genericPrice: 45.00,
    brandedPrice: 140.00,
    marketRates: [
      { shopName: 'Jan Aushadhi', price: 45.00, type: 'Generic' },
      { shopName: 'Local Chemist', price: 140.00, type: 'Branded' },
      { shopName: 'Apollo', price: 130.00, type: 'Branded' },
      { shopName: 'Truemeds', price: 60.00, type: 'Generic' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1574567675988-1f6f890693a9?auto=format&fit=crop&q=80&w=400',
    dosage: {
      normal: '1 tablet daily.',
      maxSafe: 'As prescribed.',
      overdoseWarning: 'Generally safe, excess is excreted.',
    },
    details: {
      mechanism: 'Helps in the production of myelin (nerve covering) and DNA.',
      sideEffects: ['Nausea', 'Vomiting', 'Diarrhea'],
      contraindications: ['Leber\'s disease', 'Allergy to Cobalt'],
      storage: 'Store protected from light and moisture.',
    },
  }
];

export const ANIMATIONS = {
    fadeIn: "animate-fade-in",
    slideUp: "animate-slide-up"
};